[tool.poetry]
name = "sssom-schema"
version = "0.0.0"
description = "SSSOM is a Simple Standard for Sharing Ontology Mappings."
readme = "README.md"
authors = [
    "Nicolas Matentzoglu <nicolas.matentzoglu@gmail.com>",
    "Harshad Hegde <hhegde@lbl.gov>"
    ]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
linkml-runtime = "*"
mkdocs-mermaid2-plugin = "^0.6.0"

[tool.poetry.dev-dependencies]
linkml = "^1.3.13"
mkdocs-material = "^8.2.8"

[tool.poetry.group.dev.dependencies]
linkml = "1.3.13"
linkml-runtime = "^1.3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["linkml", "mkdocs-material"]
